### POST posts
POST localhost:8080/v1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnb3BoZXJzb2NpYWwiLCJleHAiOjE3MzI5NTYxMDMsImlhdCI6MTczMjY5NjkwMywiaXNzIjoiZ29waGVyc29jaWFsIiwibmJmIjoxNzMyNjk2OTAzLCJzdWIiOjEwNX0.Ad3QlcIqkdvLYrv75_v1ghXsJB9nEqcOkD8OuLh5LYg

{
  "title": "New post",
  "content": "Hey guys this is my first post2",
  "tags": ["tags1", "tags2"]
}

### GET posts
GET localhost:8080/v1/posts/13
Content-Type: application/json

### DELETE posts
DELETE localhost:8080/v1/posts/1
Content-Type: application/json

### PATCH posts
PATCH localhost:8080/v1/posts/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnb3BoZXJzb2NpYWwiLCJleHAiOjE3MzI5NTYxMDMsImlhdCI6MTczMjY5NjkwMywiaXNzIjoiZ29waGVyc29jaWFsIiwibmJmIjoxNzMyNjk2OTAzLCJzdWIiOjEwNX0.Ad3QlcIqkdvLYrv75_v1ghXsJB9nEqcOkD8OuLh5LYg

{
  "title": "updated5",
  "content": "updated content"
}

### POST comments
POST localhost:8080/v1/posts/13/comments
Content-Type: application/json

{
  "content": "안녕하세요~ 멋진 글이네요~"
}