### GET users
GET localhost:8080/v1/users/21
Content-Type: application/json

### POST /authentication/user
POST localhost:8080/v1/authentication/user
Content-Type: application/json

{
  "email": "sdfe@gmail.com",
  "password": "sefd",
  "username": "sfe12"
}



### PUT /activate/{token}
PUT localhost:8080/v1/users/activate/c710de96-5f0e-40f9-8fdd-b4dbdb5c23bc

### POST /authentication/token
POST localhost:8080/v1/authentication/token
Content-Type: application/json

{
  "email": "sdfe@gmail.com",
  "password": "sefd"
}